<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5c5d8599bcc29',
		'title' => 'Home page options',
		'fields' => array(
			array(
				'key' => 'field_5c5d85a51508f',
				'label' => 'Top Banner',
				'name' => 'banner_section',
				'type' => 'true_false',
				'instructions' => 'Display Welcome banner?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Yes',
				'default_value' => 1,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5c5d864715090',
				'label' => 'Banner section options',
				'name' => 'banner_section_options',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5c5d85a51508f',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5c5d866515091',
						'label' => 'Home page main text',
						'name' => 'home_page_main_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '35',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Home Page	main text here.',
						'placeholder' => 'Home Page	main text here.',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5c5d86c715092',
						'label' => 'Introduction text',
						'name' => 'introduction_text',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '35',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
						'placeholder' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do	eiusmod tempor incididunt ut labor',
						'maxlength' => '',
						'rows' => 4,
						'new_lines' => 'br',
					),
					array(
						'key' => 'field_5c5d874215093',
						'label' => 'Action Button Text',
						'name' => 'action_button_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'REQUEST A FREE CONSULTATION',
						'placeholder' => 'REQUEST A FREE CONSULTATION',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5c5d879515095',
						'label' => 'Action Button link',
						'name' => 'action_button_link',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'default_value' => '#contact-us',
						'placeholder' => '#contact-us',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5c5d932bf644b',
				'label' => 'About us',
				'name' => 'about_us',
				'type' => 'true_false',
				'instructions' => 'Display About us section?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Yes',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5c5d93c5f644c',
				'label' => 'About us options',
				'name' => 'about_us_options',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5c5d932bf644b',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5c5d9437f644d',
						'label' => 'Section title',
						'name' => 'section_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'About ipsum	dolor sit amet adipiscing elit',
						'placeholder' => 'About ipsum	dolor sit amet adipiscing elit',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5c5d9495f644e',
						'label' => 'About us page Link',
						'name' => 'about_us_page_link',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'page',
						),
						'taxonomy' => '',
						'allow_null' => 0,
						'multiple' => 0,
						'return_format' => 'object',
						'ui' => 1,
					),
					array(
						'key' => 'field_5c5d94e8f644f',
						'label' => 'Read More button text',
						'name' => 'read_more_button_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Read more',
						'placeholder' => 'Read more',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5c5d9576985ee',
				'label' => 'Practice Areas',
				'name' => 'practice_areas',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Display Practice Areas?',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5c5d958c985ef',
				'label' => 'Practice Areas options',
				'name' => 'practice_areas_options',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5c5d9576985ee',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5c5d95a6985f0',
						'label' => 'Section Title',
						'name' => 'section_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Practice Areas',
						'placeholder' => 'Practice Areas',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5c5d95d9985f1',
						'label' => 'Practice Areas Items',
						'name' => 'practice_areas_items',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 4,
						'max' => 8,
						'layout' => 'table',
						'button_label' => 'Add new item',
						'sub_fields' => array(
							array(
								'key' => 'field_5c5d9632985f2',
								'label' => 'Item icon',
								'name' => 'item_icon',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '30',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'full',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => 'png,jpg,jpeg,gif,svg',
							),
							array(
								'key' => 'field_5c5d968d985f3',
								'label' => 'Item title',
								'name' => 'item_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '35',
									'class' => '',
									'id' => '',
								),
								'default_value' => 'Lorem ipsum',
								'placeholder' => 'Lorem ipsum',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5c5d96b1985f4',
								'label' => 'Item description',
								'name' => 'item_description',
								'type' => 'textarea',
								'instructions' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididun',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '35',
									'class' => '',
									'id' => '',
								),
								'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididun',
								'placeholder' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididun',
								'maxlength' => 0,
								'rows' => 2,
								'new_lines' => '',
							),
						),
					),
				),
			),
			array(
				'key' => 'field_5c5d97847a4ba',
				'label' => 'Our Attorneys',
				'name' => 'our_attorneys',
				'type' => 'true_false',
				'instructions' => 'Display Our Attorneys section?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Yes',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5c5d97a07a4bb',
				'label' => 'Our Attorneys options',
				'name' => 'our_attorneys_options',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5c5d97847a4ba',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5c5d97d07a4bc',
						'label' => 'Section title',
						'name' => 'section_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Our Attorneys',
						'placeholder' => 'Our Attorneys',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5c5d97ec7a4bd',
						'label' => 'Section description',
						'name' => 'section_description',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
						'placeholder' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
						'maxlength' => '',
						'rows' => 4,
						'new_lines' => 'br',
					),
					array(
						'key' => 'field_5c5d98267a4be',
						'label' => 'Join Us Button text',
						'name' => 'join_us_button_text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Join Us',
						'placeholder' => 'Join Us',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5c5d9cd9c607c',
						'label' => 'Our Attorneys',
						'name' => 'our_attorneys',
						'type' => 'relationship',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '105',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'attorney',
						),
						'taxonomy' => '',
						'filters' => array(
							0 => 'search',
						),
						'elements' => array(
							0 => 'featured_image',
						),
						'min' => '',
						'max' => '',
						'return_format' => 'object',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'front-page.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;